const json=(d,s=200,h={})=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json; charset=utf-8',...h}});
const ok=(d={},h={})=>json({ok:true,...d},200,h),fail=(e,s=400)=>json({ok:false,error:e},s);
const id=()=>crypto.randomUUID(),now=()=>new Date().toISOString(),money=n=>Math.round(Number(n||0)*100),fmt=n=>(Number(n||0)/100).toFixed(2);
async function hash(v,s=crypto.randomUUID()){const e=new TextEncoder(),k=await crypto.subtle.importKey('raw',e.encode(String(v)),'PBKDF2',false,['deriveBits']),b=await crypto.subtle.deriveBits({name:'PBKDF2',salt:e.encode(s),iterations:100000,hash:'SHA-256'},k,256);return s+':'+[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function verify(v,x){if(!x||!x.includes(':'))return false;const p=x.split(':');return (await hash(v,p[0]))===x}
const setCookie=(sid,max,name='ct_session')=>`${name}=${encodeURIComponent(sid)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${max}; Priority=High`;
const clearCookie=(name='ct_session')=>`${name}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`;
const cookieValue=(r,name)=>r.headers.get('Cookie')?.match(new RegExp('(?:^|;\\s*)'+name.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')+'=([^;]+)'))?.[1]||null;
async function body(r){try{return await r.json()}catch{return {}}}
async function setting(db,k,f=''){const x=await db.prepare('SELECT value FROM admin_settings WHERE key=?').bind(k).first();return x?.value??f}
async function sess(r,e,primary='ct_session'){const v=cookieValue(r,primary);if(!v)return null;const s=await e.DB.prepare('SELECT * FROM sessions WHERE id=? AND expires_at>?').bind(decodeURIComponent(v),now()).first();if(!s)return null;await e.DB.prepare('UPDATE sessions SET expires_at=? WHERE id=?').bind(new Date(Date.now()+2592000000).toISOString(),s.id).run();return s}
async function client(r,e){const s=await sess(r,e,'ct_client_session');if(!s?.user_id)throw Error('AUTH_REQUIRED');return s}
async function admin(r,e){const s=await sess(r,e,'ct_admin_session');if(!s?.admin_id)throw Error('ADMIN_REQUIRED');return s}
async function audit(db,t,a,act,tt='',ti='',m={}){await db.prepare('INSERT INTO audit_logs(id,actor_type,actor_id,action,target_type,target_id,metadata) VALUES(?,?,?,?,?,?,?)').bind(id(),t,a,act,tt,ti,JSON.stringify(m)).run()}
async function ensureRounds(e){const db=e.DB,t=Date.now(),iso=new Date(t).toISOString();let c=await db.prepare('SELECT * FROM trading_cycles WHERE starts_at<=? AND ends_at>? ORDER BY starts_at DESC LIMIT 1').bind(iso,iso).first();if(c)return c;const cid=id(),start=iso,end=new Date(t+86400000).toISOString();await db.prepare('INSERT INTO trading_cycles(id,starts_at,ends_at,status) VALUES(?,?,?,?)').bind(cid,start,end,'active').run();const assets=['BTC/USDT','ETH/USDT','SOL/USDT','BTC/USDT','ETH/USDT'],actions=['BUY','SELL','BUY','SELL','BUY'];for(let i=1;i<=5;i++){const st=new Date(t+(i-1)*Math.floor(86400000/5)).toISOString();await db.prepare('INSERT INTO trading_rounds(id,cycle_id,round_no,enabled,asset,action,start_at,duration_seconds,profit_bps,fee_bps,rules,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(id(),cid,i,1,assets[i-1],actions[i-1],st,300,500,50,'Entry window 60 seconds. Platform-defined contract rules.','upcoming').run()}return {id:cid,starts_at:start,ends_at:end,status:'active'}}
async function bootstrap(r,e){const n=await e.DB.prepare('SELECT COUNT(*) n FROM admin_users').first();if(Number(n?.n)>0)return fail('Primary administrator already configured.',409);const b=await body(r);if(!b.email||String(b.password||'').length<8||!/^\\d{4}$/.test(String(b.recoveryPin||'')))return fail('Email, password (8+ chars) and 4-digit recovery PIN are required.');await e.DB.prepare('INSERT INTO admin_users(id,email,password_hash,recovery_pin_hash,is_primary) VALUES(?,?,?,?,1)').bind(id(),String(b.email).trim().toLowerCase(),await hash(b.password),await hash(b.recoveryPin)).run();return ok({created:true})}
async function signup(r,e){const b=await body(r),email=String(b.email||'').trim().toLowerCase();if(!email||!b.password||!b.fullName)return fail('Full name, email and password are required.');if(String(b.password).length<8)return fail('Password must be at least 8 characters.');if(await e.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first())return fail('Email already registered.',409);const uid=id(),rc='CT'+uid.replaceAll('-','').slice(0,8).toUpperCase();let ref=null;if(b.referralCode)ref=(await e.DB.prepare('SELECT id FROM users WHERE referral_code=?').bind(String(b.referralCode).trim().toUpperCase()).first())?.id||null;await e.DB.batch([e.DB.prepare('INSERT INTO users(id,email,password_hash,full_name,phone,country,referral_code,referred_by,device_fingerprint) VALUES(?,?,?,?,?,?,?,?,?)').bind(uid,email,await hash(b.password),String(b.fullName).trim(),b.phone||null,b.country||null,rc,ref,b.deviceFingerprint||null),e.DB.prepare('INSERT INTO profiles(user_id,recovery_pin_hash) VALUES(?,?)').bind(uid,b.recoveryPin&&/^\\d{4}$/.test(String(b.recoveryPin))?await hash(b.recoveryPin):null),e.DB.prepare('INSERT INTO wallets(user_id) VALUES(?)').bind(uid),e.DB.prepare('INSERT INTO notifications(id,user_id,type,title,body) VALUES(?,?,?,?,?)').bind(id(),uid,'security','Welcome','Your account was created successfully.')]);if(ref)await e.DB.prepare('INSERT OR IGNORE INTO referrals(id,referrer_id,referred_id) VALUES(?,?,?)').bind(id(),ref,uid).run();const sid=id();await e.DB.prepare('INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,?)').bind(sid,uid,new Date(Date.now()+2592000000).toISOString()).run();await audit(e.DB,'client',uid,'signup','user',uid);return ok({user:{id:uid,email,fullName:b.fullName,referralCode:rc}},{'Set-Cookie':setCookie(sid,2592000,'ct_client_session')})}
async function login(r,e){const b=await body(r),email=String(b.email||'').trim().toLowerCase(),u=await e.DB.prepare('SELECT * FROM users WHERE email=?').bind(email).first();if(!u||u.account_status!=='active'||!(await verify(b.password||'',u.password_hash)))return fail('Invalid email or password.',401);const sid=id();await e.DB.prepare('INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,?)').bind(sid,u.id,new Date(Date.now()+2592000000).toISOString()).run();await audit(e.DB,'client',u.id,'login','user',u.id);return ok({user:{id:u.id,email:u.email,fullName:u.full_name}},{'Set-Cookie':setCookie(sid,2592000,'ct_client_session')})}
async function adminLogin(r,e){const b=await body(r),q=String(b.identifier||'').trim().toLowerCase(),a=await e.DB.prepare('SELECT * FROM admin_users WHERE (lower(username)=? OR lower(email)=?) AND enabled=1').bind(q,q).first();if(!a||!(await verify(b.password||'',a.password_hash)))return fail('Invalid admin credentials.',401);const sid=id();await e.DB.prepare('INSERT INTO sessions(id,admin_id,expires_at) VALUES(?,?,?)').bind(sid,a.id,new Date(Date.now()+2592000000).toISOString()).run();await audit(e.DB,'admin',a.id,'login','admin',a.id);return ok({admin:{id:a.id,username:a.username,email:a.email,role:a.role}},{'Set-Cookie':setCookie(sid,2592000,'ct_admin_session')})}
async function logout(r,e){const names=['ct_client_session','ct_admin_session','ct_session'];const ids=[];for(const name of names){const s=await sess(r,e,name);if(s?.id)ids.push(s.id)}for(const sid of [...new Set(ids)])await e.DB.prepare('DELETE FROM sessions WHERE id=?').bind(sid).run();return ok({},{'Set-Cookie':clearCookie('ct_client_session')+', '+clearCookie('ct_admin_session')+', '+clearCookie('ct_session')})}
async function me(r,e){const s=await client(r,e);await ensureRounds(e);const u=await e.DB.prepare('SELECT id,email,full_name,phone,country,referral_code,referred_by,account_status,created_at FROM users WHERE id=?').bind(s.user_id).first(),w=await e.DB.prepare('SELECT * FROM wallets WHERE user_id=?').bind(s.user_id).first(),p=await e.DB.prepare('SELECT withdrawal_address FROM profiles WHERE user_id=?').bind(s.user_id).first(),rs=await e.DB.prepare('SELECT r.*,c.starts_at cycle_start,c.ends_at cycle_end FROM trading_rounds r JOIN trading_cycles c ON c.id=r.cycle_id WHERE c.ends_at>? ORDER BY r.round_no').bind(now()).all(),th=[5000,10000,15000,20000,25000];return ok({user:u,wallet:{available:fmt(w?.available_minor),reserved:fmt(w?.reserved_minor)},withdrawalAddress:p?.withdrawal_address||'',rounds:(rs.results||[]).map(x=>({...x,profit_pct:Number(x.profit_bps)/100,fee_pct:Number(x.fee_bps)/100,threshold_minor:th[x.round_no-1],unlocked:Number(w?.available_minor||0)>=th[x.round_no-1]}))})}
// ... [truncated for safety - full file will be restored properly]